### ISSUE TITLE
Statistics for previous day is not available

### ISSUE THREAD

**Issue by Vort** [MusikAnimal/pageviews#27] opened 2016-02-20 08:24 UTC
Today (20 February 2016, 08:22 UTC) I am trying to get stats for yesterday (19 February) and I am getting nothing.
Screenshot is attached.
![wp_stats_bug](https://cloud.githubusercontent.com/assets/1242858/13195491/f631279a-d7bb-11e5-82f4-9fa41d418ec0.png)

**Comment by MusikAnimal** [comment] 2016-02-20 15:28
It usually takes around a day for the pageviews API to be populated. Here I guess it took longer than that. I am seeing data for 19 February now. I guess I could have the tool check the data for the past day and if it's `null`, assume the data isn't populated yet and hide that column from view.

**Comment by MusikAnimal** [comment] 2016-02-20 15:35
Actually, you shouldn't be able to query for 19 February until 21 February. The tool is programmed to enforce this, I think it just isn't taking into account timezones and also rounding down to a full day. Thanks for the report.

**Comment by MusikAnimal** [comment] 2016-03-04 23:23
I've pushed an update that sort of helps this... The issue is actually on the WMF-side. For some reason the API omits data for the most recent day given one date range, but with another date range the data is returned.

I could check to see if data is missing for the most recent day, then make an additional API call for that single day, but this is very hacky and not fool-proof. I'll file a phab report and we can hope WMF will fix it. Going to close this issue as won't fix for now.

**Closed by MusikAnimal** 2016-03-04 23:23 UTC
Labels: bug, wontfix

**Comment by MusikAnimal** [comment] 2016-03-04 23:47
Phab report at https://phabricator.wikimedia.org/T128925
