### ISSUE TITLE
View for 60 / 90 days not working

### ISSUE THREAD

**Issue by kipala** [MusikAnimal/pageviews#88] opened 2016-05-07 10:32 UTC
Hi, thanks for the tool, better than http://stats.grok.se, especially the possibility to compare several articles. ONLY THING I MISS: to call the 50 (or 100) most viewed pages per month / week of a specified wikipedia.

PROBLEM TO REPORT: I use it for swwiki. 30-day-view is fine. Switching to 60 or 90 days gives a flat line after the first dates.  
Example our starter page Mwanzo gets 
Totals: 25.692 in 30-day-view, but only  
Totals: 13.169  in 60-day-view   - cuts off on March 20 (my uplook is on May 7)
Totals: 39.890  in 90-day-view - cuts off again on March 20

**Comment by MusikAnimal** [comment] 2016-05-08 21:12
@kipala For the top viewed pages of any WMF wiki in a given date range, use https://tools.wmflabs.org/topviews

I'm not able to reproduce the problem you are seeing. Could you provide a link? Here is the page "Mwanzo" on swwiki over the past 60 days:
http://tools.wmflabs.org/pageviews/#project=sw.wikipedia.org&platform=all-access&agent=user&start=2016-03-09&end=2016-05-07&pages=Mwanzo

I see data for March 20 and onward. You are not seeing this data?

**Comment by kipala** [comment] 2016-05-09 09:35
1. Thanks for the tip to top pages, That is what i was looking for (with an interesting glitch - I write separately)
2. as for the pageview analysis: no, I do not see it. When I open the link above it shows until 20th, after that each day is 0.

**Comment by kipala** [comment] 2016-05-09 10:55
This is my screenshot of the link  Cheers

Ingo

**Comment by MusikAnimal** [comment] 2016-05-09 14:43
@kipala Sorry, your screen did not show up. Please link to an external site with your image uploaded.

Please also let me know:
* Which browser and version you are using (Internet Explorer 10, Chrome 50, etc)
* Operating system (Windows 7, Mac OSX, etc)
* Which language your browser is set to (try using [http://aruljohn.com/language.php](this site))

Thanks!

**Comment by kipala** [comment] 2016-05-21 14:39
**@MusikAnimal**, 
you can see my screenshot here: 
https://sw.wikipedia.org/wiki/Picha:Screen_test.png
Else I am usually on Firefox, language set is English, I use windows 7

**Comment by MusikAnimal** [comment] 2016-05-25 21:56
@kipala I'm truly at a loss here. I haven't tried on Windows 7 yet, but that shouldn't matter.

Does this issue happen only for swwiki? Try:
https://tools.wmflabs.org/pageviews/?project=en.wikipedia.org&platform=all-access&agent=user&start=2016-02-25&end=2016-05-24&pages=Cat|Dog

So you see data for all 90 days?

Also try our Siteviews tool, which uses the same API to show the total number of views a wiki receives. Here are the last 90 days for swwiki:
http://tools.wmflabs.org/siteviews/?platform=all-access&source=pageviews&agent=user&range=latest-90&sites=sw.wikipedia.org

Do you see all 90 days of data for this tool?

**Comment by kipala** [comment] 2016-05-26 06:01
Hi

Thanks for the hints, same result for all views. 60 days fine, 90 days cut off.

 

AND I tried the view on my wifes McAirbook , same result.

Can it have to do with the country I am in? (Iran…)  Sometimes I run into blocks because of my adress.

 

Anyway, your toll is still fine even without 90 days.

 

Cheers

**Comment by MusikAnimal** [comment] 2016-07-01 05:26
@kipala I have made a lot of major changes since we last spoke. Any change the 60/90 day view is working for you now?

**Comment by MusikAnimal** [comment] 2016-10-27 21:50
Closing due as unreproducible. @kipala if you are still running into this issue let me know and I will try to help you one on one :)

**Closed by MusikAnimal** 2016-10-27 21:50 UTC
Labels: Needs test case
