### ISSUE TITLE
Pageviews in all languages in which the article is existing

### ISSUE THREAD

**Issue by itzike** [MusikAnimal/pageviews#51] opened 2016-04-03 11:30 UTC
Will be super useful to have an option to select an article (like Wikipedia for example) and to see breakdown of all the pageviews in each language that the article is existing

**Comment by MusikAnimal** [comment] 2016-04-04 20:04
Currently in development! I hope to have something out within a week or two. Duplicate of #11

**Comment by MusikAnimal** [comment] 2016-04-18 16:26
@itzike I've got a beta-ish version up and running at https://tools.wmflabs.org/langviews

Let me know what you think! :)

**Comment by itzike** [comment] 2016-04-19 20:11
Works amazing!
Thank you!

**Comment by MusikAnimal** [comment] 2016-04-25 01:40
Closing

**Closed by MusikAnimal** 2016-04-25 01:40 UTC
Labels: duplicate
